/**
 * AgentPay ABI — single source of truth for the frontend.
 *
 * This file is a verbatim copy of:
 *   Blockchain/artifacts-export/AgentPay.json
 *
 * Do NOT edit this file manually.
 * To update: re-copy from the Blockchain repo after recompilation.
 *   cp ../Blockchain/artifacts-export/AgentPay.json ./src/abi/AgentPay.json
 */
import artifact from './AgentPay.json';

/** @type {import('ethers').InterfaceAbi} */
export const AGENT_PAY_ABI = artifact.abi;

export default AGENT_PAY_ABI;
